export { HeroSection } from './HeroSection'
export { AboutSection } from './AboutSection'
export { SkillsSection } from './SkillsSection'
export { ProjectsSection } from './ProjectsSection'
export { ProcessSection } from './ProcessSection'
export { ExperienceSection } from './ExperienceSection'
export { EducationSection } from './EducationSection'
export { ContactSection } from './ContactSection'
